CREATE TABLE t (
  WatchID BIGINT,
  JavaEnable SMALLINT,
  Title TEXT ENCODING DICT(32),
  GoodEvent SMALLINT,
  EventTime BIGINT,
  EventDate INTEGER,
  CounterID INTEGER,
  ClientIP INTEGER,
  RegionID INTEGER,
  UserID BIGINT,
  CounterClass SMALLINT,
  OS SMALLINT,
  UserAgent SMALLINT,
  URL TEXT ENCODING DICT(32),
  Referer TEXT ENCODING DICT(32),
  IsRefresh SMALLINT,
  RefererCategoryID SMALLINT,
  RefererRegionID INTEGER,
  URLCategoryID SMALLINT,
  URLRegionID INTEGER,
  ResolutionWidth SMALLINT,
  ResolutionHeight SMALLINT,
  ResolutionDepth SMALLINT,
  FlashMajor SMALLINT,
  FlashMinor SMALLINT,
  FlashMinor2 TEXT ENCODING DICT(32),
  NetMajor SMALLINT,
  NetMinor SMALLINT,
  UserAgentMajor SMALLINT,
  UserAgentMinor TEXT ENCODING DICT(32),
  CookieEnable SMALLINT,
  JavascriptEnable SMALLINT,
  IsMobile SMALLINT,
  MobilePhone SMALLINT,
  MobilePhoneModel TEXT ENCODING DICT(32),
  Params TEXT ENCODING DICT(32),
  IPNetworkID INTEGER,
  TraficSourceID SMALLINT,
  SearchEngineID SMALLINT,
  SearchPhrase TEXT ENCODING DICT(32),
  AdvEngineID SMALLINT,
  IsArtifical SMALLINT,
  WindowClientWidth SMALLINT,
  WindowClientHeight SMALLINT,
  ClientTimeZone SMALLINT,
  ClientEventTime BIGINT,
  SilverlightVersion1 SMALLINT,
  SilverlightVersion2 SMALLINT,
  SilverlightVersion3 INTEGER,
  SilverlightVersion4 SMALLINT,
  PageCharset TEXT ENCODING DICT(32),
  CodeVersion INTEGER,
  IsLink SMALLINT,
  IsDownload SMALLINT,
  IsNotBounce SMALLINT,
  FUniqID BIGINT,
  OriginalURL TEXT ENCODING DICT(32),
  HID INTEGER,
  IsOldCounter SMALLINT,
  IsEvent SMALLINT,
  IsParameter SMALLINT,
  DontCountHits SMALLINT,
  WithHash SMALLINT,
  HitColor TEXT ENCODING DICT(32),
  LocalEventTime BIGINT,
  Age SMALLINT,
  Sex SMALLINT,
  Income SMALLINT,
  Interests SMALLINT,
  Robotness SMALLINT,
  RemoteIP INTEGER,
  WindowName INTEGER,
  OpenerName INTEGER,
  HistoryLength SMALLINT,
  BrowserLanguage TEXT ENCODING DICT(32),
  BrowserCountry TEXT ENCODING DICT(32),
  SocialNetwork TEXT ENCODING DICT(32),
  SocialAction TEXT ENCODING DICT(32),
  HTTPError SMALLINT,
  SendTiming INTEGER,
  DNSTiming INTEGER,
  ConnectTiming INTEGER,
  ResponseStartTiming INTEGER,
  ResponseEndTiming INTEGER,
  FetchTiming INTEGER,
  SocialSourceNetworkID SMALLINT,
  SocialSourcePage TEXT ENCODING DICT(32),
  ParamPrice BIGINT,
  ParamOrderID TEXT ENCODING DICT(32),
  ParamCurrency TEXT ENCODING DICT(32),
  ParamCurrencyID SMALLINT,
  OpenstatServiceName TEXT ENCODING DICT(32),
  OpenstatCampaignID TEXT ENCODING DICT(32),
  OpenstatAdID TEXT ENCODING DICT(32),
  OpenstatSourceID TEXT ENCODING DICT(32),
  UTMSource TEXT ENCODING DICT(32),
  UTMMedium TEXT ENCODING DICT(32),
  UTMCampaign TEXT ENCODING DICT(32),
  UTMContent TEXT ENCODING DICT(32),
  UTMTerm TEXT ENCODING DICT(32),
  FromTag TEXT ENCODING DICT(32),
  HasGCLID SMALLINT,
  RefererHash BIGINT,
  URLHash BIGINT,
  CLID INTEGER
);
